
[[render]]
id = "UNO-Game"
main = "render/game/public/main.js"
webroot = "render/game/public"

[[render]]
id = "UNO-Home"
main = "render/home/public/main.js"
webroot = "render/home/public"

[[render]]
id = "UNO-Player"
main = "render/player/public/main.js"
webroot = "render/player/public"
